services:
    byproxy:
        container_name: byproxy
        image: timconner/byproxy
        ports:
            - 80:80
            - 443:443
            - 8081:8081
        volumes:
            - ./byproxy:/app/data
        restart: unless-stopped
